### ISSUE TITLE
Feature Request: Consider a tap vs hold option

### ISSUE THREAD

**Issue by Vashinator** [system76/launch#84] opened 2023-04-15 15:31 UTC
This isn't as big of a deal to me as #83 
But it would be a nice feature to be able to have a tap vs held option when configuring a key. 

Some ideas I've seen:
- having caps when a letter is held down (though that may be a keyboard wide setting). 
- Doing more with caps lock by using the tap to be standard caps lock and hold to be a combo of modifier keys.
- Using the Fn key, a tap switches the layer until it's tapped again,  a hold only has the layer active while it's being held.

**Comment by leviport** [comment] 2023-04-17 13:56
Duplicate of https://github.com/pop-os/keyboard-configurator/issues/64

Since Launch uses QMK firmware, this is already supported, but firmware must be [manually customized and flashed](https://github.com/system76/qmk_firmware/blob/master/keyboards/system76/launch_1/readme.md), rather than mapped using the Configurator. Support for more advanced functionality, including mod-tap is [currently being worked on](https://github.com/pop-os/keyboard-configurator/issues/64).

**Closed by leviport** 2023-04-17 13:56 UTC
